### ISSUE TITLE
New Fixed IP for P2P

### ISSUE THREAD

**Issue by Geordie-R** [eon-llc/rem-utils#6]
Im changing my IP to my new reserved IP.  Also doing a server move. Also changing the domain. 

Please see new entry below

p2p.bp.geordier.co.uk = 45.77.91.94

Note: old address of producerprimary.geordier.co.uk will also point to the new IP for historical reasons but im retiring it in favour of p2p.bp.geordier.co.uk.

**Comment by sergchernata** [comment]
Done.
